development:
  secret_key_base: secret
  devise: secret
  google_analytics:
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>