development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>

test:
  secret_key_base: test
  devise: test
  google_analytics:
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>
