production:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
development:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
test:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
